replicaCount: 2

image:
  repository: ghcr.io/infobeans-vishalmene/devops-platform
  tag: "041d09bf2e70ffa9e4ce17114ceac2ea4db068a7"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

containerPort: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

labels:
  app: devops-platform